version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    image: virgo22/food_frontend:v1
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: foodgram_nginx
    image: nginx:1.19.3
    # В этом контейнере не используем, можно выпилить.
#    env_file:
#      - .env
    ports:
#      - "8000:80"  # для запуска на сервере (внешний:внутренний)
      # Для локального запуска localhost/admin, localhosta.
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/foodgram/static
      - media:/foodgram/media
    depends_on:
      - backend
      - frontend

  backend:
    container_name: foodgram_backend
    build: ../backend/
    # Лучше это сделать руками для отладки.
    # А как все будет работать в git-action перенести.
#    command: |
#      bash -c 'python manage.py migrate &&
#      python manage.py collectstatic --noinput &&
#      cp -r /app/collected_static/. /app/static/ &&
#      gunicorn --bind 0:8000 foodgram.wsgi'
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db